apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgCkZy9D1TK8f5uat3xARLYgFn8lezwmlznSxgCDT8I/poBQEJREMb2iYGsRfa5Q4P0Hb4toGKFROwp0J1zUnzT1TuLTsKOxO+CB3elga/aFBmmAptsFmM/HDiCdpMaLAd2ScNoKPkHBwN65cX5t6A70wBe4efimFjzZj+lcmN4OHiWHhSalf2ePRpImzaH5aV84P2r6Pzomdl/xMOaMPShiMO+XB9SwpxVQimUsyOKpgqKG8OvzJaDbWkCbYjTEBJWMBNanSoBuYvWrg9Fm581Zc58eUX21LTmRF6qkALDdgpoPR7uEgyX4XljwQ5G7OIYminoGZmn0JDamm1Xh9AS5tm8ZVfOoIjXaKER1kE7RARac/JEDon+k01dsBakqjeI0sdnulsM3Y9vZL1mUmSrqQC6gC7SVC2xMCCwajT8Pu2vdQ9B+p57O79qqCkuU+nM0jDPXqVYJLHTvDWsM8kS1e5kOkfxSIDucfX5iAam70MZoydL21GFtNHr7wqZ3S6QpEbACS3u2VKHN8K8IoVcZisasFy0xke5PYJrt0LoPe5KwFWf5+xjG2AJt9UdWfVonktEHNo1erY7YHoZJRnykDs3Y2nVKOHwsgUG+Tr060PFKuvdrb/5Fch4yQEVswlMNjpeG2kcuOznz+OoLrD9cp8iELE9bnm9pxCDGdq6cJpzFlX4FEJbduTV/SICFYwRmL8JBagT1kFuu4fWm3OTIdVFGjpFNZvIzNLLfjnZbYRTcAKRpyeR5LZJWwzQ3565iehKjvWuHHtCEoC/lyGcMj5dkxW/oxNLuM6F431+RlJZOJin3pOMXlxxprRqp8/t8We0mHPxnqW6/d4q1b15vVwwoJOS0BzsXrz+RHk6lzuhgNRnPikGC0bIqhH3nHnBkYa1Wg+2T2bq4+950coJ4/wnb0D+LUetX5j9REbGg7DOQ82nyP1mD5G3fj+v99dwCk6fuIR+f1zDj59QoE2AQu3rdsQT3Fp1nA2GvN7UE/bk=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull
      namespace: dev
    type: kubernetes.io/dockerconfigjson

