apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull
  namespace: prod
spec:
  encryptedData:
    .dockerconfigjson: AgA/bYtJ1clz8gvuqgfHTvhqsjzVogHLCxY0ERw9r0rFzTe7PWmLEuvxm3ipOWzo3jSFY1bSUaIrrWz01QjkRJMbqZDjLKb+PuFoyD9+xUbqSbMTC46JxYQ5t4Ux4s0btZN7SFjm9KvBrklud2Fp2n9k6IFaigkKVZITRdFWIFHMfqwd0xEuXywDF6rg/WqrpsP28TxDP80Kr2QHwcE+TRPIQQgmHwgeTLBTsVss5nWwyAn7NdB09zKLnTJwFwTyTXypw2foLcKRFntihB0FLiNTR0WscMErNJ4cowD/Ll+s1O3UmHTbB70R4jTXdKnR22Vp0qoh+N5E05vFJp02kYp6BsaAQnPM2ZppW5vHw0Ny73IxwzbipMOJ6BcvYlcjDPMPCghyFvTTEsca0L5O9nDH8W1iJL2jr61cwtzc5hZcf4HRGBdamzIhu1K6UNMR+4XRIsVA6pww+Izj9RAzOF2bFEi587lrZdHzwGnsXV4VpszI3iS+28J9Ho5sUGwKt7z29WHdIeyPc1MVJB0HsYbyvqwgZUtk7sU58z5X38GHqG52j2QotWMpQjFpUb/RI56yoathV9DCMntZD0Dq7d/ECRilZF2HpfCy2ItWZVXVyCG0ncBsp+JkWL7zA9WpMS94lD+T6qNqb24isgRxeig6DH6F1KwdNRQhEiIXbPVSIgbcEdltk9k3mK06x2rysRN4Ycbl7EowyJqjVmCs59OUqYh2StrqxHoWWlZHFV5W1olsfN+szc1GGCZelEe7iKTvPctXobuxemfyDVAl0r8vQD21hvKnQgMLT98BLVWlUz/R6TMjgTz7rPmJ3j5l8zWdMOKxmtW+nNCcoXK4IN4A7RbCpeMtP2ooKhUp9+FObF1FSKLt5EI53xeueygF6W/JS2cIobpNPT7kLbzObKrzHZyRbzKtrgrrEAdrH3rfsLlaG5vY39WHL/8n42DjtmLpKl0ctMgHrpMCGgdonhIJHnlTJPwRRlr49yOP0YvOlCg=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull
      namespace: prod
    type: kubernetes.io/dockerconfigjson

